// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Rating struct {
	ID        string
	WineID    string
	UserID    string
	Rating    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	Token     string
	UserID    string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             string
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Wine struct {
	ID        string
	Color     string
	Name      string
	Producer  string
	Country   string
	Vintage   int64
	CreatedBy string
	CreatedAt time.Time
	UpdatedAt time.Time
}
