// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ratings.sql

package database

import (
	"context"
)

const createRating = `-- name: CreateRating :one
INSERT INTO ratings (
    id,
    wine_id,
    user_id,
    rating
) VALUES (?, ?, ?, ?)
RETURNING id, wine_id, user_id, created_at, updated_at, rating
`

type CreateRatingParams struct {
	ID     string
	WineID string
	UserID string
	Rating string
}

func (q *Queries) CreateRating(ctx context.Context, arg CreateRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, createRating,
		arg.ID,
		arg.WineID,
		arg.UserID,
		arg.Rating,
	)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.WineID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rating,
	)
	return i, err
}

const deleteAllRatings = `-- name: DeleteAllRatings :exec
DELETE FROM ratings
`

func (q *Queries) DeleteAllRatings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllRatings)
	return err
}

const getRatingByID = `-- name: GetRatingByID :one
SELECT id, wine_id, user_id, created_at, updated_at, rating
FROM ratings
WHERE ID = ?
`

func (q *Queries) GetRatingByID(ctx context.Context, id string) (Rating, error) {
	row := q.db.QueryRowContext(ctx, getRatingByID, id)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.WineID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rating,
	)
	return i, err
}

const updateRatingByID = `-- name: UpdateRatingByID :one
UPDATE ratings
SET
    rating = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE ID = ?
RETURNING id, wine_id, user_id, created_at, updated_at, rating
`

type UpdateRatingByIDParams struct {
	Rating string
	ID     string
}

func (q *Queries) UpdateRatingByID(ctx context.Context, arg UpdateRatingByIDParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, updateRatingByID, arg.Rating, arg.ID)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.WineID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rating,
	)
	return i, err
}
